language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvlc-dev vlc-nox libjack-jackd2-dev

before_script:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.7.tar.gz
  - tar -f libsodium-1.0.7.tar.gz -xv
  - pushd libsodium-1.0.7
  - ./configure && make && sudo make install
  - popd
  - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz
  - tar -f zeromq-4.1.3.tar.gz -xv
  - pushd zeromq-4.1.3
  - ./configure && make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

