language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvlc-dev vlc-nox libjack-jackd2-dev

before_script:
  - wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz -o /tmp/libsodium.tar.gz
  - tar -f /tmo/libsodium.tar.gz -x
  - pushd libsodium-*
  - ./configure && make && sudo make install
  - popd
  - wget http://download.zeromq.org/zeromq-4.1.3.tar.gz -o /tmp/zeromq.tar.gz
  - tar -f /tmp/zeromq.tar.gz -x
  - pushd zeromq-*
  - ./configure && make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

