language: c
sudo: false

addons:
  apt:
    packages:
      - libvlc-dev
      - vlc-nox
      - libjack-jackd2-dev
      - libzmq3-dev
      - libzmq3


compiler:
  - gcc
  - clang

before_script:
  - pkg-config --modversion libzmq

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

