language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install -y libvlc-dev vlc-nox libjack-jackd2-dev
  - pkg-config --modversion libzmq

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

