language: c

compiler:
  - gcc
  - clang

before_script:
  - sudo add-apt-repository ppa:chris-lea/zeromq -y
  - sudo add-apt-repository ppa:chris-lea/libsodium -y
  - sudo apt-get update -qq
  - sudo apt-get install -y libvlc-dev vlc-nox libjack-jackd2-dev libzmq5-dev libzmq5
  - pkg-config --modversion libzmq || true
  - pkg-config --modversion libzmq3 || true

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

