language: c
sudo: required
dist: trusty

compiler:
  - gcc
  - clang

addons: &addons
  apt:
    packages: &packages
      - libzmq3-dev
      - libzmq3

script:
  - mkdir build
  - cd build
  - cmake ..
  - make

